# Plotly

-  Python library used for creating interactive and publication-quality
graphs. It supports a wide range of visualizations including line charts, scatter
plots, bar charts, 3D charts, and maps.
- An open-source graphing library that makes interactive, publication-quality
graphs.
- Available in Python, R, Julia, and JavaScript.

# Installation

pip install plotly

# Importing

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
import plotly.express as px

In [ ]:
data=px.data.gapminder()
data

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
data_canada=px.data.gapminder().query("country=='Canada'")
data_canada

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952   68.750  14785584  11367.16112       CAN      124
241  Canada  Americas  1957   69.960  17010154  12489.95006       CAN      124
242  Canada  Americas  1962   71.300  18985849  13462.48555       CAN      124
243  Canada  Americas  1967   72.130  20819767  16076.58803       CAN      124
244  Canada  Americas  1972   72.880  22284500  18970.57086       CAN      124
245  Canada  Americas  1977   74.210  23796400  22090.88306       CAN      124
246  Canada  Americas  1982   75.760  25201900  22898.79214       CAN      124
247  Canada  Americas  1987   76.860  26549700  26626.51503       CAN      124
248  Canada  Americas  1992   77.950  28523502  26342.88426       CAN      124
249  Canada  Americas  1997   78.610  30305843  28954.92589       CAN      124
250  Canada  Americas  2002   79.770  31902268  33328.96507       CAN      124
251  Canada  Americas  2007   80.653  33390141  36319.23501       CAN      124

In [ ]:
fig = px.bar(data_canada,x='pop', y='year', orientation='v')
fig.show()

In [ ]:
fig1=px.bar(data_canada,x='pop',y='year',color='pop',text='year',height=400)
fig1.show()

In [ ]:
fig1=px.bar(data_canada,x='pop',y='year',hover_data=['lifeExp', 'gdpPercap'],color='pop',text='pop',height=400)
fig1.update_traces(textposition='outside')
fig1.show()

In [ ]:
import plotly.io as pio
pio.templates

Templates configuration
-----------------------
    Default template: 'plotly'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none']

In [ ]:
fig2=px.bar(data_canada,x='pop',y='year',hover_data=['lifeExp', 'gdpPercap'],color='pop',text='pop',template='plotly_dark')
fig2.update_traces(textposition='outside')
fig2.show()

In [ ]:
fig2=px.bar(data_canada,x='pop',y='year',hover_data=['lifeExp', 'gdpPercap'],color='pop',text='pop',template='seaborn')
fig2.update_traces(textposition='outside')
fig2.show()

In [ ]:
fig2=px.bar(data_canada,x='pop',y='year',hover_data=['lifeExp', 'gdpPercap'],color='pop',text='pop',template='ggplot2')
fig2.update_traces(textposition='outside')
fig2.show()

In [ ]:
df=px.data.gapminder().query("continent == 'Oceania'")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
60,Australia,Oceania,1952,69.120,8691212,10039.59564,AUS,36
61,Australia,Oceania,1957,70.330,9712569,10949.64959,AUS,36
62,Australia,Oceania,1962,70.930,10794968,12217.22686,AUS,36
63,Australia,Oceania,1967,71.100,11872264,14526.12465,AUS,36
64,Australia,Oceania,1972,71.930,13177000,16788.62948,AUS,36
65,Australia,Oceania,1977,73.490,14074100,18334.19751,AUS,36
66,Australia,Oceania,1982,74.740,15184200,19477.00928,AUS,36
67,Australia,Oceania,1987,76.320,16257249,21888.88903,AUS,36
68,Australia,Oceania,1992,77.560,17481977,23424.76683,AUS,36
69,Australia,Oceania,1997,78.830,18565243,26997.93657,AUS,36
70,Australia,Oceania,2002,80.370,19546792,30687.75473,AUS,36
71,Australia,Oceania,2007,81.235,20434176,34435.36744,AUS,36
1092,New Zealand,Oceania,1952,69.390,1994794,10556.57566,NZL,554
1093,New Zealand,Oceania,1957,70.260,2229407,12247.39532,NZL,554
1094,New Zealand,Oceania,1962,71.240,2488550,13175.67800,NZL,554
1095,New Zealand,Oceania,1967,71.520,2728150,14463.91893,NZL,554
1096,New Zealand,Oceania,1972,71.890,2929100,16046.03728,NZL,554
1097,New Zealand,Oceania,1977,72.220,3164900,16233.71770,NZL,554
1098,New Zealand,Oceania,1982,73.840,3210650,17632.41040,NZL,554
1099,New Zealand,Oceania,1987,74.320,3317166,19007.19129,NZL,554
1100,New Zealand,Oceania,1992,76.330,3437674,18363.32494,NZL,554
1101,New Zealand,Oceania,1997,77.550,3676187,21050.41377,NZL,554
1102,New Zealand,Oceania,2002,79.110,3908037,23189.80135,NZL,554
1103,New Zealand,Oceania,2007,80.204,4115771,25185.00911,NZL,554

In [ ]:
fig=px.bar(df, x='year', y='pop',hover_data=['country','lifeExp', 'gdpPercap'], color='country',labels={'pop':'population of country'},height=400)
fig.show()

In [ ]:
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='country',
             labels={'pop':'population of Canada'}, height=500,barmode = 'group')
fig.show()

In [ ]:
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='country',
             labels={'pop':'population of Canada'}, height=500,barmode = 'stack')
fig.show()

In [ ]:
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='country',
             labels={'pop':'population of Canada'}, height=500,barmode = 'overlay')
fig.show()

In [ ]:
data1=px.data.gapminder().query("continent == 'Oceania' and year==2007 and pop > 2.e6")
data1

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
71,Australia,Oceania,2007,81.235,20434176,34435.36744,AUS,36
1103,New Zealand,Oceania,2007,80.204,4115771,25185.00911,NZL,554

In [ ]:
fig=px.bar(data1,y='pop', x='country',text_auto='.3s',title="Default: various text sizes, positions and angles")
fig.show()

In [ ]:
fig = px.bar(df, y='pop', x='country', text_auto='.2s',
            title="Controlled text sizes, positions and angles")
fig.update_traces(textfont_size=12, textangle=0, textposition="inside")
fig.show()

In [ ]:
long_df = px.data.medals_long()
long_df

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [ ]:
fig = px.bar(long_df, x="nation", y="count", color="medal", title="Long-Form Input")
fig.show()

In [ ]:
fig = px.bar(long_df, x="nation", y="count", color="medal",pattern_shape="medal",pattern_shape_sequence=[".", "x", "+"])
fig.show()

In [ ]:
fig = px.bar(long_df, x="nation", y="count", color="medal",barmode='group', title="Long-Form Input")
fig.show()

In [ ]:
df = px.data.gapminder().query("country=='Canada'")
fig = px.line(df, x="year", y="lifeExp", title='Life expectancy in Canada')
fig.show()

In [ ]:
df = px.data.gapminder().query("continent=='Oceania'")
fig = px.line(df, x="year", y="lifeExp", color='country')
fig.show()

In [ ]:
df = px.data.gapminder().query("continent == 'Oceania'")
fig = px.line(df, x='year', y='lifeExp', color='country', markers=True)
fig.show()

In [ ]:
df = px.data.gapminder()
fig = px.line(df, x="year", y="lifeExp", color='country')
fig.show()

In [ ]:
df = px.data.gapminder().query("country in ['Canada', 'Botswana']")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
156,Botswana,Africa,1952,47.622,442308,851.241141,BWA,72
157,Botswana,Africa,1957,49.618,474639,918.232535,BWA,72
158,Botswana,Africa,1962,51.520,512764,983.653976,BWA,72
159,Botswana,Africa,1967,53.298,553541,1214.709294,BWA,72
160,Botswana,Africa,1972,56.024,619351,2263.611114,BWA,72
161,Botswana,Africa,1977,59.319,781472,3214.857818,BWA,72
162,Botswana,Africa,1982,61.484,970347,4551.142150,BWA,72
163,Botswana,Africa,1987,63.622,1151184,6205.883850,BWA,72
164,Botswana,Africa,1992,62.745,1342614,7954.111645,BWA,72
165,Botswana,Africa,1997,52.556,1536536,8647.142313,BWA,72
166,Botswana,Africa,2002,46.634,1630347,11003.605080,BWA,72
167,Botswana,Africa,2007,50.728,1639131,12569.851770,BWA,72
240,Canada,Americas,1952,68.750,14785584,11367.161120,CAN,124
241,Canada,Americas,1957,69.960,17010154,12489.950060,CAN,124
242,Canada,Americas,1962,71.300,18985849,13462.485550,CAN,124
243,Canada,Americas,1967,72.130,20819767,16076.588030,CAN,124
244,Canada,Americas,1972,72.880,22284500,18970.570860,CAN,124
245,Canada,Americas,1977,74.210,23796400,22090.883060,CAN,124
246,Canada,Americas,1982,75.760,25201900,22898.792140,CAN,124
247,Canada,Americas,1987,76.860,26549700,26626.515030,CAN,124
248,Canada,Americas,1992,77.950,28523502,26342.884260,CAN,124
249,Canada,Americas,1997,78.610,30305843,28954.925890,CAN,124
250,Canada,Americas,2002,79.770,31902268,33328.965070,CAN,124
251,Canada,Americas,2007,80.653,33390141,36319.235010,CAN,124

In [ ]:
df = px.data.gapminder().query("country in ['Canada', 'Botswana']")

fig = px.line(df, x="lifeExp", y="gdpPercap", color="country", text="year")
fig.update_traces(textposition="bottom right")
fig.show()

In [ ]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100
383,Croatia,Europe,2007,75.748,4493312,14619.222720,HRV,191
407,Czech Republic,Europe,2007,76.486,10228744,22833.308510,CZE,203
419,Denmark,Europe,2007,78.332,5468120,35278.418740,DNK,208
527,Finland,Europe,2007,79.313,5238460,33207.084400,FIN,246
539,France,Europe,2007,80.657,61083916,30470.016700,FRA,250
575,Germany,Europe,2007,79.406,82400996,32170.374420,DEU,276
599,Greece,Europe,2007,79.483,10706290,27538.411880,GRC,300
683,Hungary,Europe,2007,73.338,9956108,18008.944440,HUN,348
695,Iceland,Europe,2007,81.757,301931,36180.789190,ISL,352
755,Ireland,Europe,2007,78.885,4109086,40675.996350,IRL,372
779,Italy,Europe,2007,80.546,58147733,28569.719700,ITA,380
1019,Montenegro,Europe,2007,74.543,684736,9253.896111,MNE,499
1091,Netherlands,Europe,2007,79.762,16570613,36797.933320,NLD,528
1151,Norway,Europe,2007,80.196,4627926,49357.190170,NOR,578
1235,Poland,Europe,2007,75.563,38518241,15389.924680,POL,616
1247,Portugal,Europe,2007,78.098,10642836,20509.647770,PRT,620
1283,Romania,Europe,2007,72.476,22276056,10808.475610,ROU,642
1343,Serbia,Europe,2007,74.002,10150265,9786.534714,SRB,688
1379,Slovak Republic,Europe,2007,74.663,5447502,18678.314350,SVK,703
1391,Slovenia,Europe,2007,77.926,2009245,25768.257590,SVN,705
1427,Spain,Europe,2007,80.941,40448191,28821.063700,ESP,724
1475,Sweden,Europe,2007,80.884,9031088,33859.748350,SWE,752
1487,Switzerland,Europe,2007,81.701,7554661,37506.419070,CHE,756
1583,Turkey,Europe,2007,71.777,71158647,8458.276384,TUR,792
1607,United Kingdom,Europe,2007,79.425,60776238,33203.261280,GBR,826

In [ ]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
fig = px.pie(df, values='pop', names='gdpPercap', title='Population of European continent')
fig.show()

In [ ]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
df.loc[df['pop'] < 2.e6, 'country'] = 'Other countries' # Represent only large countries
fig = px.pie(df, values='pop', names='gdpPercap', title='Population of European continent')
fig.show()

In [ ]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
fig = px.pie(df, values='pop', names='country',
             title='Population of American continent')
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

In [ ]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
fig = px.pie(df, values='pop', names='country',
             title='Population of American continent',
             hover_data=['lifeExp'], labels={'lifeExp':'life expectancy'})
fig.update_traces(textposition='inside', textinfo='percent+label', marker=dict( line=dict(color='#000000', width=2)))
fig.show()

In [ ]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
fig = px.pie(df, values='total_bill', names='day')
fig.show()

In [ ]:
fig = px.pie(df, values='tip', names='day', hole=.5)
fig.show()

In [ ]:
fig = px.pie(df, values='tip', names='day', color='day',
             color_discrete_map={'Thur':'lightcyan',
                                 'Fri':'cyan',
                                 'Sat':'royalblue',
                                 'Sun':'darkblue'})
fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
fig.show()

In [ ]:
df = px.data.gapminder()
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [ ]:
fig = px.scatter(df, x="year", y="pop")
fig.show()

In [ ]:
de = px.data.gapminder().query("continent == 'Oceania'")

fig = px.scatter(de, x="year", y="pop", color="country",hover_data=['country'])
fig.show()

In [ ]:
fig = px.scatter(de, x="year", y="pop", color="country",size='pop', hover_data=['country'])
fig.show()

In [ ]:
fig = px.scatter(de, x="year", y="pop", color="year",size='pop', hover_data=['country'])
fig.show()

In [ ]:
fig = px.scatter(de, x="year", y="pop", color="country",size='pop', hover_data=['country'],symbol="country")
fig.show()

In [ ]:
fig = px.scatter(de, x="year", y="pop", color="country",hover_data=['country'],symbol="country")
fig.update_traces(marker_size=10)
fig.show()

In [ ]:
fig = px.scatter(de, x="year", y="pop", color="country",hover_data=['country'],symbol="country")
fig.update_traces(marker_size=20)
fig.show()

In [ ]:
fig = px.scatter(de, y="pop", x="lifeExp",color="country", marginal_x="histogram", marginal_y="rug")
fig.show()

In [ ]:
fig = px.scatter(de, y="pop", x="lifeExp", color="country",  facet_col="year")
fig.show()

In [ ]:
fig = px.scatter(de, x="year", y="pop",trendline="ols")
fig.show()

In [ ]:
fig = px.scatter(df.query("year==2007"), x="gdpPercap", y="lifeExp",size="pop", color="continent",hover_name="country", log_x=True,size_max=60)
fig.show()

In [ ]:
fig = px.scatter(df.query("year==2007"), x="gdpPercap", y="lifeExp",size="pop", color="continent",hover_name="country", log_y=True,size_max=60)
fig.show()

In [ ]:
fig = px.area(df, x="year", y="pop", color="country",line_group="country")
fig.show()

In [ ]:
fig = px.area(df, x="year", y="pop", color="continent", line_group="country",pattern_shape="continent")
fig.show()

In [ ]:
import numpy as np
df = px.data.gapminder().query("year == 2007")
fig = px.sunburst(df, path=['continent', 'country'], values='pop',
                  color='lifeExp', hover_data=['iso_alpha'],
                  color_continuous_scale='RdBu',
                  color_continuous_midpoint=np.average(df['lifeExp'], weights=df['pop']))
fig.show()

In [ ]:
df1 = px.data.tips()
df1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
fig = px.sunburst(df1, path=['day', 'time', 'sex'], values='total_bill')
fig.show()

In [ ]:
fig = px.sunburst(df1, path=['day', 'time'], values='total_bill')
fig.show()

In [ ]:
fig = px.icicle(df1, path=[px.Constant("all"), 'day', 'time', 'sex'],values='total_bill', color='day')
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [ ]:
fig = px.icicle(df1, path=[px.Constant("all"), 'sex', 'day', 'time'],values='total_bill', color='day')
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [ ]:
fig = px.icicle(df1, path=[px.Constant("all"), 'sex', 'day', 'time'],
                values='total_bill', color='time')
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [ ]:
df = px.data.gapminder().query("year == 2007")
fig = px.icicle(df, path=[px.Constant("world"), 'continent', 'country'], values='pop',
                  color='pop', hover_data=['iso_alpha'],
                  color_continuous_scale='RdBu')
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [ ]:
import pandas as pd
import plotly.express as px

df = px.data.gapminder()

# Filter data for Europe in years 1952 and 2002
df = df[(df.continent == "Europe") & (df.year.isin([1952, 2002]))]

# Sorting countries by life expectancy in 2002
countries_sorted = df[df.year == 2002].sort_values(by="lifeExp")["country"].unique()
df["country"] = pd.Categorical(df["country"], categories=countries_sorted, ordered=True)

# Reshape data for proper line drawing
df_lines = df.pivot(index="country", columns="year", values="lifeExp").reset_index()
df_lines = df_lines.melt(id_vars=["country"], var_name="year", value_name="lifeExp")
df_lines

                   country  year  lifeExp
0                   Turkey  1952   43.585
1                  Romania  1952   61.050
2                 Bulgaria  1952   59.600
3                  Hungary  1952   64.030
4                   Serbia  1952   57.996
5          Slovak Republic  1952   64.360
6               Montenegro  1952   59.164
7   Bosnia and Herzegovina  1952   53.820
8                   Poland  1952   61.310
9                  Croatia  1952   61.210
10          Czech Republic  1952   66.870
11                 Albania  1952   55.230
12                Slovenia  1952   65.570
13                 Denmark  1952   70.780
14                Portugal  1952   59.820
15                 Ireland  1952   66.910
16                  Greece  1952   65.860
17                 Belgium  1952   68.000
18                 Finland  1952   66.550
19          United Kingdom  1952   69.180
20             Netherlands  1952   72.130
21                 Germany  1952   67.500
22                 Austria  1952   66.800
23                  Norway  1952   72.670
24                  France  1952   67.410
25                   Spain  1952   64.940
26                  Sweden  1952   71.860
27                   Italy  1952   65.940
28                 Iceland  1952   72.490
29             Switzerland  1952   69.620
30                  Turkey  2002   70.845
31                 Romania  2002   71.322
32                Bulgaria  2002   72.140
33                 Hungary  2002   72.590
34                  Serbia  2002   73.213
35         Slovak Republic  2002   73.800
36              Montenegro  2002   73.981
37  Bosnia and Herzegovina  2002   74.090
38                  Poland  2002   74.670
39                 Croatia  2002   74.876
40          Czech Republic  2002   75.510
41                 Albania  2002   75.651
42                Slovenia  2002   76.660
43                 Denmark  2002   77.180
44                Portugal  2002   77.290
45                 Ireland  2002   77.783
46                  Greece  2002   78.256
47                 Belgium  2002   78.320
48                 Finland  2002   78.370
49          United Kingdom  2002   78.471
50             Netherlands  2002   78.530
51                 Germany  2002   78.670
52                 Austria  2002   78.980
53                  Norway  2002   79.050
54                  France  2002   79.590
55                   Spain  2002   79.780
56                  Sweden  2002   80.040
57                   Italy  2002   80.240
58                 Iceland  2002   80.500
59             Switzerland  2002   80.620

In [ ]:

# Create the line chart connecting 1952 and 2002
fig = px.line(
    df_lines,
    x="lifeExp",
    y="country",
    line_group="country",
    markers=True,
    title="Life Expectancy in Europe: 1952 and 2002",
    labels={"lifeExp": "Life Expectancy", "country": "Country", "year": "Year"},
    height=1000
)
# Update marker colors (Green for 1952, Blue for 2002)
fig.update_traces(marker=dict(size=10))


# Show the figure
fig.show()

In [ ]:
import plotly.express as px
import numpy as np
df = px.data.medals_wide(indexed=True)
df

medal        gold  silver  bronze
nation
South Korea    24      13      11
China          10      15       8
Canada          9      12      12

In [ ]:
fig = px.imshow(df)
fig.show()

In [ ]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# Select only numeric columns explicitly
numeric_df = df.select_dtypes(include=['float64', 'int64'])

# Compute correlation matrix
corr_matrix = numeric_df.corr()
corr_matrix

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [ ]:
# Plot interactive heatmap
fig = px.imshow(
    corr_matrix,
    text_auto=True,
    color_continuous_scale='RdBu_r',
    title='Tips Dataset - Correlation Heatmap'
)

fig.update_layout(width=600, height=500)

fig.show()

In [ ]:
df = px.data.tips()
fig = px.histogram(df, x="sex")
fig.show()

In [ ]:
df = px.data.tips()
fig = px.histogram(df, x="total_bill")
fig.show()

In [ ]:
fig = px.histogram(df, x="total_bill", nbins=5)
fig.show()

In [ ]:
counts, bins = np.histogram(df.total_bill, bins=range(0, 60, 5))
bins = 0.5 * (bins[:-1] + bins[1:])

fig = px.bar(x=bins, y=counts, labels={'x':'total_bill', 'y':'count'})
fig.show()

In [ ]:
fig = px.histogram(df, x="day", category_orders=dict(day=["Thur", "Fri", "Sat", "Sun"]))
fig.show()

In [ ]:
fig = px.histogram(df, x="day", y="total_bill", category_orders=dict(day=["Thur", "Fri", "Sat", "Sun"]))
fig.show()

In [ ]:
fig = px.histogram(df, x="day", y="total_bill", color="sex", category_orders=dict(day=["Thur", "Fri", "Sat", "Sun"]))
fig.show()

In [ ]:
fig = px.histogram(df, x="total_bill", color="sex")
fig.show()

In [ ]:
import pandas as pd

df = pd.DataFrame([
    dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28'),
    dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15'),
    dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30')
])

fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task")
fig.show()

In [ ]:
import pandas as pd

df = pd.DataFrame([
    dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28'),
    dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15'),
    dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30')
])

fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task")
fig.update_yaxes(autorange="reversed") # otherwise tasks are listed from the bottom up
fig.show()

In [ ]:
df = pd.DataFrame([
    dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28', Resource="Alex"),
    dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15', Resource="Alex"),
    dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30', Resource="Max")
])

fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task", color="Resource")
fig.update_yaxes(autorange="reversed")
fig.show()

In [ ]:
df = pd.DataFrame([
    dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28', Completion_pct=50),
    dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15', Completion_pct=25),
    dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30', Completion_pct=75)
])

fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task", color="Completion_pct")
fig.update_yaxes(autorange="reversed")
fig.show()

In [ ]:
import plotly.figure_factory as ff

df = [dict(Task="Job-1", Start='2017-01-01', Finish='2017-02-02', Resource='Complete'),
      dict(Task="Job-1", Start='2017-02-15', Finish='2017-03-15', Resource='Incomplete'),
      dict(Task="Job-2", Start='2017-01-17', Finish='2017-02-17', Resource='Not Started'),
      dict(Task="Job-2", Start='2017-01-17', Finish='2017-02-17', Resource='Complete'),
      dict(Task="Job-3", Start='2017-03-10', Finish='2017-03-20', Resource='Not Started'),
      dict(Task="Job-3", Start='2017-04-01', Finish='2017-04-20', Resource='Not Started'),
      dict(Task="Job-3", Start='2017-05-18', Finish='2017-06-18', Resource='Not Started'),
      dict(Task="Job-4", Start='2017-01-14', Finish='2017-03-14', Resource='Complete')]

colors = {'Not Started': 'rgb(220, 0, 0)',
          'Incomplete': (1, 0.9, 0.16),
          'Complete': 'rgb(0, 255, 100)'}

fig = ff.create_gantt(df, colors=colors, index_col='Resource', show_colorbar=True,
                      group_tasks=True)
fig.show()

In [ ]:
import pandas as pd

# Sample data: List of project tasks with start and end dates
data = pd.DataFrame({
    "Task": ["Planning", "Design", "Development", "Testing", "Deployment"],
    "Start": ["2024-03-01", "2024-03-10", "2024-03-20", "2024-04-05", "2024-04-15"],
    "End": ["2024-03-09", "2024-03-19", "2024-04-04", "2024-04-14", "2024-04-20"]
})

# Convert date columns to datetime format
data["Start"] = pd.to_datetime(data["Start"])
data["End"] = pd.to_datetime(data["End"])

# Create Gantt chart using plotly
fig = px.timeline(data, x_start="Start", x_end="End", y="Task", title="Project Timeline")

# Reverse order so tasks are listed from top to bottom
fig.update_yaxes(categoryorder="total ascending")

# Show the chart
fig.show()

In [ ]:
import plotly.express as px
import pandas as pd

# Sample data: Task name, Start date, Duration (in days), and Precedence
data = pd.DataFrame({
    "Task": ["Planning", "Design", "Development", "Testing", "Deployment"],
    "Start": ["2024-03-01", "2024-03-01", "2024-03-01", "2024-03-01", "2024-03-01"],  # Start only for the first task
    "Duration": [9, 10, 15, 9, 5],  # Duration in days
    "Precedence": [None, "Planning", "Design", "Development", "Testing"]  # Dependencies
})

# Convert Start column to datetime format
data["Start"] = pd.to_datetime(data["Start"])

# Calculate Start Dates based on Precedence
for i in range(1, len(data)):  # Start from index 1 since index 0 (Planning) has a fixed start date
    predecessor = data.loc[i, "Precedence"]
    if pd.notna(predecessor):  # If there's a dependent task
        prev_end = data.loc[data["Task"] == predecessor, "Start"].values[0] + pd.to_timedelta(data.loc[data["Task"] == predecessor, "Duration"].values[0], unit="D")
        data.at[i, "Start"] = prev_end  # Assign start after the predecessor ends

# Calculate End Dates
data["End"] = data["Start"] + pd.to_timedelta(data["Duration"], unit="D")

# Create Gantt chart
fig = px.timeline(data, x_start="Start", x_end="End", y="Task", title="Project Timeline with Dependencies")

# Reverse order for better readability
fig.update_yaxes(categoryorder="total ascending")

# Show the chart
fig.show()